--------------------------------------------------------
--  File created - Friday-May-10-2024   
--------------------------------------------------------
-- Create a new user
--------------------------------------------------------
CREATE USER TM IDENTIFIED BY "TM";
--------------------------------------------------------
-- Grant permissions to the user
--------------------------------------------------------
GRANT ALL PRIVILEGES TO TM;
--------------------------------------------------------
--  DDL for Sequence OFFENCE_DETAILS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TM"."OFFENCE_DETAILS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OFFENCE_TYPES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TM"."OFFENCE_TYPES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TM"."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VEHICLES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TM"."VEHICLES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OFFENCE_DETAILS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TM"."OFFENCE_DETAILS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OFFENCE_TYPES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TM"."OFFENCE_TYPES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TM"."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VEHICLES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TM"."VEHICLES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table OFFENCE_DETAILS
--------------------------------------------------------

  CREATE TABLE "TM"."OFFENCE_DETAILS" 
   (	"OFFENSE_DETAIL_ID" VARCHAR2(20 BYTE), 
	"OFFENSE_DATE_TIME" TIMESTAMP (6), 
	"PLACE" VARCHAR2(200 BYTE), 
	"IMAGE" BLOB, 
	"REGISTRATION_ID" VARCHAR2(13 BYTE), 
	"OFFENSE_ID" VARCHAR2(10 BYTE), 
	"RECORDED_BY" VARCHAR2(10 BYTE), 
	"PENALTY_STATUS" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("IMAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table OFFENCE_TYPES
--------------------------------------------------------

  CREATE TABLE "TM"."OFFENCE_TYPES" 
   (	"OFFENSE_ID" VARCHAR2(10 BYTE), 
	"OFFENSE_NAME" VARCHAR2(50 BYTE), 
	"VEHICLE_TYPE" VARCHAR2(50 BYTE), 
	"PENALTY" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OWNERS
--------------------------------------------------------

  CREATE TABLE "TM"."OWNERS" 
   (	"OWNER_ID" VARCHAR2(12 BYTE), 
	"ID_TYPE" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"DATEOFBIRTH" DATE, 
	"GENDER" VARCHAR2(6 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"PINCODE" NUMBER, 
	"OCCUPATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REGISTRATIONS
--------------------------------------------------------

  CREATE TABLE "TM"."REGISTRATIONS" 
   (	"REGISTRATION_ID" VARCHAR2(13 BYTE), 
	"VEHICLE_ID" NUMBER, 
	"OWNER_ID" VARCHAR2(12 BYTE), 
	"REGISTRATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "TM"."ROLES" 
   (	"ROLENAME" VARCHAR2(20 BYTE), 
	"ROLE_DESCRIPTION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "TM"."USERS" 
   (	"USER_ID" VARCHAR2(10 BYTE), 
	"USER_NAME" VARCHAR2(10 BYTE), 
	"PASSWORD" VARCHAR2(16 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"ROLENAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEHICLES
--------------------------------------------------------

  CREATE TABLE "TM"."VEHICLES" 
   (	"VEHICLE_ID" NUMBER, 
	"ENGINE_NUMBER" VARCHAR2(30 BYTE), 
	"CHASSIS_NUMBER" VARCHAR2(30 BYTE), 
	"VEHICLE_TYPE" VARCHAR2(20 BYTE), 
	"VEH_COLOR" VARCHAR2(20 BYTE), 
	"FUEL_USED" VARCHAR2(20 BYTE), 
	"MANUFACTURE_DATE" DATE, 
	"MANUFACTURER_NAME" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(30 BYTE), 
	"MODEL_NO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OFFENCE_TYPES
--------------------------------------------------------

  CREATE TABLE "TM"."OFFENCE_TYPES" 
   (	"OFFENSE_ID" VARCHAR2(10 BYTE), 
	"OFFENSE_NAME" VARCHAR2(50 BYTE), 
	"VEHICLE_TYPE" VARCHAR2(50 BYTE), 
	"PENALTY" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REGISTRATIONS
--------------------------------------------------------

  CREATE TABLE "TM"."REGISTRATIONS" 
   (	"REGISTRATION_ID" VARCHAR2(13 BYTE), 
	"VEHICLE_ID" NUMBER, 
	"OWNER_ID" VARCHAR2(12 BYTE), 
	"REGISTRATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "TM"."USERS" 
   (	"USER_ID" VARCHAR2(10 BYTE), 
	"USER_NAME" VARCHAR2(10 BYTE), 
	"PASSWORD" VARCHAR2(16 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"ROLENAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OWNERS
--------------------------------------------------------

  CREATE TABLE "TM"."OWNERS" 
   (	"OWNER_ID" VARCHAR2(12 BYTE), 
	"ID_TYPE" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"DATEOFBIRTH" DATE, 
	"GENDER" VARCHAR2(6 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"PINCODE" NUMBER, 
	"OCCUPATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEHICLES
--------------------------------------------------------

  CREATE TABLE "TM"."VEHICLES" 
   (	"VEHICLE_ID" NUMBER, 
	"ENGINE_NUMBER" VARCHAR2(30 BYTE), 
	"CHASSIS_NUMBER" VARCHAR2(30 BYTE), 
	"VEHICLE_TYPE" VARCHAR2(20 BYTE), 
	"VEH_COLOR" VARCHAR2(20 BYTE), 
	"FUEL_USED" VARCHAR2(20 BYTE), 
	"MANUFACTURE_DATE" DATE, 
	"MANUFACTURER_NAME" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(30 BYTE), 
	"MODEL_NO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "TM"."ROLES" 
   (	"ROLENAME" VARCHAR2(20 BYTE), 
	"ROLE_DESCRIPTION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OFFENCE_DETAILS
--------------------------------------------------------

  CREATE TABLE "TM"."OFFENCE_DETAILS" 
   (	"OFFENSE_DETAIL_ID" VARCHAR2(20 BYTE), 
	"OFFENSE_DATE_TIME" TIMESTAMP (6), 
	"PLACE" VARCHAR2(200 BYTE), 
	"IMAGE" BLOB, 
	"REGISTRATION_ID" VARCHAR2(13 BYTE), 
	"OFFENSE_ID" VARCHAR2(10 BYTE), 
	"RECORDED_BY" VARCHAR2(10 BYTE), 
	"PENALTY_STATUS" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("IMAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into TM.OFFENCE_DETAILS
SET DEFINE OFF;
REM INSERTING into TM.OFFENCE_TYPES
SET DEFINE OFF;
REM INSERTING into TM.OWNERS
SET DEFINE OFF;
REM INSERTING into TM.REGISTRATIONS
SET DEFINE OFF;
REM INSERTING into TM.ROLES
SET DEFINE OFF;
REM INSERTING into TM.USERS
SET DEFINE OFF;
REM INSERTING into TM.VEHICLES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index OFFENCE_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."OFFENCE_DETAILS_PK" ON "TM"."OFFENCE_DETAILS" ("OFFENSE_DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OFFENCE_TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."OFFENCE_TYPES_PK" ON "TM"."OFFENCE_TYPES" ("OFFENSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OWNERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."OWNERS_PK" ON "TM"."OWNERS" ("OWNER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REGISTRATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."REGISTRATIONS_PK" ON "TM"."REGISTRATIONS" ("REGISTRATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."ROLES_PK" ON "TM"."ROLES" ("ROLENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_EMAIL_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."USERS_EMAIL_UK" ON "TM"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."USERS_PK" ON "TM"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VEHICLES_CHASSIS_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."VEHICLES_CHASSIS_UK" ON "TM"."VEHICLES" ("CHASSIS_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VEHICLES_ENG_NO_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."VEHICLES_ENG_NO_UK" ON "TM"."VEHICLES" ("ENGINE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VEHICLES_MODEL_NO_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."VEHICLES_MODEL_NO_UK" ON "TM"."VEHICLES" ("MODEL_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VEHICLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."VEHICLES_PK" ON "TM"."VEHICLES" ("VEHICLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OFFENCE_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."OFFENCE_DETAILS_PK" ON "TM"."OFFENCE_DETAILS" ("OFFENSE_DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OFFENCE_TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."OFFENCE_TYPES_PK" ON "TM"."OFFENCE_TYPES" ("OFFENSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OWNERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."OWNERS_PK" ON "TM"."OWNERS" ("OWNER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REGISTRATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."REGISTRATIONS_PK" ON "TM"."REGISTRATIONS" ("REGISTRATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."ROLES_PK" ON "TM"."ROLES" ("ROLENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."USERS_PK" ON "TM"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_EMAIL_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."USERS_EMAIL_UK" ON "TM"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VEHICLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."VEHICLES_PK" ON "TM"."VEHICLES" ("VEHICLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VEHICLES_CHASSIS_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."VEHICLES_CHASSIS_UK" ON "TM"."VEHICLES" ("CHASSIS_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VEHICLES_ENG_NO_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."VEHICLES_ENG_NO_UK" ON "TM"."VEHICLES" ("ENGINE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VEHICLES_MODEL_NO_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TM"."VEHICLES_MODEL_NO_UK" ON "TM"."VEHICLES" ("MODEL_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger OFFENCE_DETAILS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TM"."OFFENCE_DETAILS_TRIGGER" 
BEFORE INSERT ON offence_details
FOR EACH ROW
BEGIN
  :new.OFFENSE_DETAIL_ID := 'OFD' || LPAD(offence_details_seq.NEXTVAL, 3, '0');
END;
/
ALTER TRIGGER "TM"."OFFENCE_DETAILS_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OFFENE_TYPES_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TM"."OFFENE_TYPES_TRIGGER" 
BEFORE INSERT ON offence_types
FOR EACH ROW
BEGIN
  :new.OFFENSE_ID := 'OF' || LPAD(offence_types_seq.NEXTVAL, 3, '0');
END;
/
ALTER TRIGGER "TM"."OFFENE_TYPES_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TM"."USERS_TRIGGER" 
BEFORE INSERT ON users
FOR EACH ROW
BEGIN
  :new.USER_ID := 'U' || LPAD(USERS_SEQ.nextval, 3, '0');
END;
/
ALTER TRIGGER "TM"."USERS_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VEHICLES_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TM"."VEHICLES_TRIGGER" 
BEFORE INSERT ON vehicles
FOR EACH ROW
BEGIN
  :new.VEHICLE_ID := VEHICLES_SEQ.nextval;
END;
/
ALTER TRIGGER "TM"."VEHICLES_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OFFENCE_DETAILS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TM"."OFFENCE_DETAILS_TRIGGER" 
BEFORE INSERT ON offence_details
FOR EACH ROW
BEGIN
  :new.OFFENSE_DETAIL_ID := 'OFD' || LPAD(offence_details_seq.NEXTVAL, 3, '0');
END;
/
ALTER TRIGGER "TM"."OFFENCE_DETAILS_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OFFENE_TYPES_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TM"."OFFENE_TYPES_TRIGGER" 
BEFORE INSERT ON offence_types
FOR EACH ROW
BEGIN
  :new.OFFENSE_ID := 'OF' || LPAD(offence_types_seq.NEXTVAL, 3, '0');
END;
/
ALTER TRIGGER "TM"."OFFENE_TYPES_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TM"."USERS_TRIGGER" 
BEFORE INSERT ON users
FOR EACH ROW
BEGIN
  :new.USER_ID := 'U' || LPAD(USERS_SEQ.nextval, 3, '0');
END;
/
ALTER TRIGGER "TM"."USERS_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VEHICLES_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TM"."VEHICLES_TRIGGER" 
BEFORE INSERT ON vehicles
FOR EACH ROW
BEGIN
  :new.VEHICLE_ID := VEHICLES_SEQ.nextval;
END;
/
ALTER TRIGGER "TM"."VEHICLES_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table OFFENCE_DETAILS
--------------------------------------------------------

  ALTER TABLE "TM"."OFFENCE_DETAILS" ADD CONSTRAINT "OFFENCE_DETAILS_PK" PRIMARY KEY ("OFFENSE_DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TM"."OFFENCE_DETAILS" MODIFY ("PENALTY_STATUS" NOT NULL ENABLE);
  ALTER TABLE "TM"."OFFENCE_DETAILS" MODIFY ("RECORDED_BY" NOT NULL ENABLE);
  ALTER TABLE "TM"."OFFENCE_DETAILS" MODIFY ("OFFENSE_ID" NOT NULL ENABLE);
  ALTER TABLE "TM"."OFFENCE_DETAILS" MODIFY ("REGISTRATION_ID" NOT NULL ENABLE);
  ALTER TABLE "TM"."OFFENCE_DETAILS" MODIFY ("OFFENSE_DETAIL_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OFFENCE_TYPES
--------------------------------------------------------

  ALTER TABLE "TM"."OFFENCE_TYPES" ADD CONSTRAINT "OFFENCE_TYPES_PK" PRIMARY KEY ("OFFENSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TM"."OFFENCE_TYPES" MODIFY ("PENALTY" NOT NULL ENABLE);
  ALTER TABLE "TM"."OFFENCE_TYPES" MODIFY ("VEHICLE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "TM"."OFFENCE_TYPES" MODIFY ("OFFENSE_NAME" NOT NULL ENABLE);
  ALTER TABLE "TM"."OFFENCE_TYPES" MODIFY ("OFFENSE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OWNERS
--------------------------------------------------------

  ALTER TABLE "TM"."OWNERS" MODIFY ("OCCUPATION" NOT NULL ENABLE);
  ALTER TABLE "TM"."OWNERS" MODIFY ("PINCODE" NOT NULL ENABLE);
  ALTER TABLE "TM"."OWNERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "TM"."OWNERS" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "TM"."OWNERS" MODIFY ("DATEOFBIRTH" NOT NULL ENABLE);
  ALTER TABLE "TM"."OWNERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "TM"."OWNERS" MODIFY ("ID_TYPE" NOT NULL ENABLE);
  ALTER TABLE "TM"."OWNERS" MODIFY ("OWNER_ID" NOT NULL ENABLE);
  ALTER TABLE "TM"."OWNERS" ADD CONSTRAINT "OWNERS_PK" PRIMARY KEY ("OWNER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGISTRATIONS
--------------------------------------------------------

  ALTER TABLE "TM"."REGISTRATIONS" ADD CONSTRAINT "REGISTRATIONS_PK" PRIMARY KEY ("REGISTRATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TM"."REGISTRATIONS" MODIFY ("REGISTRATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "TM"."REGISTRATIONS" MODIFY ("OWNER_ID" NOT NULL ENABLE);
  ALTER TABLE "TM"."REGISTRATIONS" MODIFY ("VEHICLE_ID" NOT NULL ENABLE);
  ALTER TABLE "TM"."REGISTRATIONS" MODIFY ("REGISTRATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "TM"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("ROLENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TM"."ROLES" MODIFY ("ROLENAME" NOT NULL ENABLE);
  ALTER TABLE "TM"."ROLES" MODIFY ("ROLE_DESCRIPTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "TM"."USERS" ADD CONSTRAINT "USERS_EMAIL_UK" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TM"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TM"."USERS" MODIFY ("ROLENAME" NOT NULL ENABLE);
  ALTER TABLE "TM"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "TM"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "TM"."USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "TM"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEHICLES
--------------------------------------------------------

  ALTER TABLE "TM"."VEHICLES" ADD CONSTRAINT "VEHICLES_MODEL_NO_UK" UNIQUE ("MODEL_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TM"."VEHICLES" ADD CONSTRAINT "VEHICLES_ENG_NO_UK" UNIQUE ("ENGINE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TM"."VEHICLES" ADD CONSTRAINT "VEHICLES_CHASSIS_UK" UNIQUE ("CHASSIS_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TM"."VEHICLES" ADD CONSTRAINT "VEHICLES_PK" PRIMARY KEY ("VEHICLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TM"."VEHICLES" MODIFY ("MODEL_NO" NOT NULL ENABLE);
  ALTER TABLE "TM"."VEHICLES" MODIFY ("MODEL" NOT NULL ENABLE);
  ALTER TABLE "TM"."VEHICLES" MODIFY ("MANUFACTURE_DATE" NOT NULL ENABLE);
  ALTER TABLE "TM"."VEHICLES" MODIFY ("VEHICLE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "TM"."VEHICLES" MODIFY ("ENGINE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "TM"."VEHICLES" MODIFY ("VEHICLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table OFFENCE_DETAILS
--------------------------------------------------------

  ALTER TABLE "TM"."OFFENCE_DETAILS" ADD CONSTRAINT "OFFENCE_DETAILS_OFF_FK" FOREIGN KEY ("OFFENSE_ID")
	  REFERENCES "TM"."OFFENCE_TYPES" ("OFFENSE_ID") ENABLE;
  ALTER TABLE "TM"."OFFENCE_DETAILS" ADD CONSTRAINT "OFFENCE_DETAILS_REC_BY_FK" FOREIGN KEY ("RECORDED_BY")
	  REFERENCES "TM"."USERS" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TM"."OFFENCE_DETAILS" ADD CONSTRAINT "OFFENCE_DETAILS_REG_FK" FOREIGN KEY ("REGISTRATION_ID")
	  REFERENCES "TM"."REGISTRATIONS" ("REGISTRATION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGISTRATIONS
--------------------------------------------------------

  ALTER TABLE "TM"."REGISTRATIONS" ADD CONSTRAINT "REGISTRATIONS_OWN_ID_FK" FOREIGN KEY ("OWNER_ID")
	  REFERENCES "TM"."OWNERS" ("OWNER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TM"."REGISTRATIONS" ADD CONSTRAINT "REGISTRATIONS_VEH_ID_FK" FOREIGN KEY ("VEHICLE_ID")
	  REFERENCES "TM"."VEHICLES" ("VEHICLE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "TM"."USERS" ADD CONSTRAINT "USERS_ROLE_FK" FOREIGN KEY ("ROLENAME")
	  REFERENCES "TM"."ROLES" ("ROLENAME") ON DELETE CASCADE ENABLE;
