/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms.presentation.TrafficCop;

import tms.presentation.Login.LoginPage;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import tms.business.TcopOperations;
import tms.business.impl.TcopOperationsImpl;
import tms.persistence.entity.OffenceDetailEO;
import tms.persistence.entity.OffenceTypeEO;
import tms.persistence.entity.OwnerEO;
import tms.persistence.entity.RegistrationEO;
import tms.persistence.entity.UserEO;
import tms.persistence.entity.VehicleEO;
import tms.persistence.utility.Validator;
import tms.presentation.Clerk.ClerkPage;

/**
 *
 * @author bhagya.shree
 */
public class TrafficCopPage extends javax.swing.JFrame {

    private TcopOperations cop = new TcopOperationsImpl();

    /**
     * Creates new form TrafficCopPage
     */
    public TrafficCopPage() {
        initComponents();
        //scaleImage();
        addRoleList();
        setVisible(Boolean.TRUE);
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        TCopOper = new javax.swing.JTabbedPane();
        tabCopHome = new javax.swing.JPanel();
        labelWcCop = new javax.swing.JLabel();
        labelCopBgimg = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        tabRaiseOffence = new javax.swing.JPanel();
        panelCopRaiseOffence = new javax.swing.JPanel();
        labelRaiseOffenceByCopTitle = new javax.swing.JLabel();
        labelOffenceDateTimeToAddByCop = new javax.swing.JLabel();
        labelPlaceToAddByCop = new javax.swing.JLabel();
        labelProofToAddByCop = new javax.swing.JLabel();
        labelVehicleNoToAddByCop = new javax.swing.JLabel();
        labelOffenceIDToAddByCop = new javax.swing.JLabel();
        labelRecordedByToAddByCop = new javax.swing.JLabel();
        labelPenaltyStatusToAddByCop = new javax.swing.JLabel();
        btnRaiseOffenceByCop = new javax.swing.JButton();
        spinOffenceDateTimeToAddByCop = new javax.swing.JSpinner();
        txtfldRecordedByToAddByCop = new javax.swing.JTextField();
        txtfldVehicleNoToAddByCop = new javax.swing.JTextField();
        txtfldPlaceToAddByCop = new javax.swing.JTextField();
        comBoxOffenceIDToRaiseByCop = new javax.swing.JComboBox<>();
        comBoxPenaltyStatusToAddByCop = new javax.swing.JComboBox<>();
        btnProofToAddByCop = new javax.swing.JButton();
        tabClearOffence = new javax.swing.JPanel();
        panelCopClearOffence = new javax.swing.JPanel();
        labelClearOffenceByCop = new javax.swing.JLabel();
        txtfldSearchHistoryToClearByCop = new javax.swing.JTextField();
        labelSearchHistoryToClearByCop = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableViewHistoryToClearByCaop = new javax.swing.JTable();
        btnClearOffence = new javax.swing.JButton();
        btnSearchHistoryToClearByCop = new javax.swing.JButton();
        tabViewHistory = new javax.swing.JPanel();
        panelViewHistoryByCop = new javax.swing.JPanel();
        labelViewOffenceHistoryByCop = new javax.swing.JLabel();
        labelSearchHistoryToViewByCop = new javax.swing.JLabel();
        txtfldSearchHistoryToViewByCop = new javax.swing.JTextField();
        togBtnViewHistoryToViewByCop = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableViewHistoryToViewByCaop = new javax.swing.JTable();
        tabAutoProfiles = new javax.swing.JPanel();
        scrollpaneViewDetails = new javax.swing.JScrollPane();
        panelDetails = new javax.swing.JPanel();
        labelSearchDetailsToViewByCop = new javax.swing.JLabel();
        labelAutoProfileByCop = new javax.swing.JLabel();
        txtfldSearchDetailsToViewByCop = new javax.swing.JTextField();
        checkVehicleDetailsByCop = new javax.swing.JCheckBox();
        checOwnerDetailsByCop = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        labelForViewOwnerDetails = new javax.swing.JLabel();
        labelOwnerIDToviewByCop = new javax.swing.JLabel();
        labelIDTypeToViewByCop = new javax.swing.JLabel();
        labelDobToViewByCop = new javax.swing.JLabel();
        labelFirstNameToViewByCop = new javax.swing.JLabel();
        labelLastNameToViewByCop = new javax.swing.JLabel();
        labelGenderToViewByCop = new javax.swing.JLabel();
        labelMobileNOToViewByCop = new javax.swing.JLabel();
        labelAddressToViewByCop = new javax.swing.JLabel();
        labelPincodeToViewByCop = new javax.swing.JLabel();
        labelOccupationToViewByCop = new javax.swing.JLabel();
        txtfldPincodeToViewByCop = new javax.swing.JTextField();
        txtfldMobileNoToViewByCop = new javax.swing.JTextField();
        txtfieldFirstNameToViewByCop = new javax.swing.JTextField();
        txtfldLastNameToViewByCop = new javax.swing.JTextField();
        txtfldOwnerIDToViewByCop = new javax.swing.JTextField();
        txtfldOccupationToViewByCop = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaAddressToViewByCop = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        labelForViewOwnerDetails4 = new javax.swing.JLabel();
        labelEngineNumberToViewByCop = new javax.swing.JLabel();
        labelTypeToViewByCop = new javax.swing.JLabel();
        labelFuelUsedToViewByCop = new javax.swing.JLabel();
        labelChasisNoToViewByCop = new javax.swing.JLabel();
        labelBrandToViewByCop = new javax.swing.JLabel();
        labelColorToViewByCop = new javax.swing.JLabel();
        labelManuNameToViewByCop = new javax.swing.JLabel();
        labelManuDateToViewByCop = new javax.swing.JLabel();
        labelModelNoToViewByCop = new javax.swing.JLabel();
        labelVehicleIDToViewByCop = new javax.swing.JLabel();
        txtfldEngineNumberToViewByCop = new javax.swing.JTextField();
        txtfldChasisNoToViewByCop = new javax.swing.JTextField();
        txtfldFuelUsedToViewByCop = new javax.swing.JTextField();
        txtfldBrandToViewByCop = new javax.swing.JTextField();
        txtfldColorToViewByCop = new javax.swing.JTextField();
        txtfldManuNameToViewByCop = new javax.swing.JTextField();
        txtfldModelNoToViewByCop = new javax.swing.JTextField();
        txtfldVehicleIDToViewByCop = new javax.swing.JTextField();
        btnBackToHomeFromAutoProfilesByCop = new javax.swing.JButton();
        btnSearchDetailsoViewByCop = new javax.swing.JButton();
        txtfldTypeToViewByCop = new javax.swing.JTextField();
        txtfldenderToViewByCop = new javax.swing.JTextField();
        txtfldDTypeToViewByCop = new javax.swing.JTextField();
        txtfldDobToViewByCop = new javax.swing.JTextField();
        txtfldManuDateToViewByCop = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TCopOper.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        TCopOper.setPreferredSize(getSize());

        labelWcCop.setFont(new java.awt.Font("Bodoni MT", 2, 70)); // NOI18N
        labelWcCop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWcCop.setText("Welcome Cop..!");

        labelCopBgimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCopBgimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tms/presentation/icons/Cop.jpg"))); // NOI18N
        labelCopBgimg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnLogout.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCopHomeLayout = new javax.swing.GroupLayout(tabCopHome);
        tabCopHome.setLayout(tabCopHomeLayout);
        tabCopHomeLayout.setHorizontalGroup(
            tabCopHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCopBgimg, javax.swing.GroupLayout.DEFAULT_SIZE, 1886, Short.MAX_VALUE)
            .addGroup(tabCopHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addComponent(labelWcCop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tabCopHomeLayout.setVerticalGroup(
            tabCopHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCopHomeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelWcCop)
                .addGap(28, 28, 28)
                .addComponent(labelCopBgimg, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addGap(148, 148, 148))
        );

        TCopOper.addTab("Home", tabCopHome);

        panelCopRaiseOffence.setLayout(new java.awt.GridBagLayout());

        labelRaiseOffenceByCopTitle.setFont(new java.awt.Font("Times New Roman", 3, 40)); // NOI18N
        labelRaiseOffenceByCopTitle.setForeground(new java.awt.Color(204, 0, 51));
        labelRaiseOffenceByCopTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRaiseOffenceByCopTitle.setText("Raise Offence");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 1040;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 0, 0);
        panelCopRaiseOffence.add(labelRaiseOffenceByCopTitle, gridBagConstraints);

        labelOffenceDateTimeToAddByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelOffenceDateTimeToAddByCop.setText("Offence Date and Time");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 381, 0, 0);
        panelCopRaiseOffence.add(labelOffenceDateTimeToAddByCop, gridBagConstraints);

        labelPlaceToAddByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelPlaceToAddByCop.setText("Place");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 115;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 381, 0, 0);
        panelCopRaiseOffence.add(labelPlaceToAddByCop, gridBagConstraints);

        labelProofToAddByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelProofToAddByCop.setText("Proof");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 381, 0, 0);
        panelCopRaiseOffence.add(labelProofToAddByCop, gridBagConstraints);

        labelVehicleNoToAddByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelVehicleNoToAddByCop.setText("Vehicle Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 381, 0, 0);
        panelCopRaiseOffence.add(labelVehicleNoToAddByCop, gridBagConstraints);

        labelOffenceIDToAddByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelOffenceIDToAddByCop.setText("Offence ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 381, 0, 0);
        panelCopRaiseOffence.add(labelOffenceIDToAddByCop, gridBagConstraints);

        labelRecordedByToAddByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelRecordedByToAddByCop.setText("Recorded By");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 381, 0, 0);
        panelCopRaiseOffence.add(labelRecordedByToAddByCop, gridBagConstraints);

        labelPenaltyStatusToAddByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelPenaltyStatusToAddByCop.setText("Penalty Status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(56, 381, 0, 0);
        panelCopRaiseOffence.add(labelPenaltyStatusToAddByCop, gridBagConstraints);

        btnRaiseOffenceByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        btnRaiseOffenceByCop.setText("Raise offence");
        btnRaiseOffenceByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseOffenceByCopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(56, 551, 32, 0);
        panelCopRaiseOffence.add(btnRaiseOffenceByCop, gridBagConstraints);

        spinOffenceDateTimeToAddByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        spinOffenceDateTimeToAddByCop.setModel(new javax.swing.SpinnerDateModel());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(67, 68, 0, 0);
        panelCopRaiseOffence.add(spinOffenceDateTimeToAddByCop, gridBagConstraints);

        txtfldRecordedByToAddByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldRecordedByToAddByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldRecordedByToAddByCopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 193;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 70, 0, 0);
        panelCopRaiseOffence.add(txtfldRecordedByToAddByCop, gridBagConstraints);

        txtfldVehicleNoToAddByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldVehicleNoToAddByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldVehicleNoToAddByCopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 193;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 70, 0, 0);
        panelCopRaiseOffence.add(txtfldVehicleNoToAddByCop, gridBagConstraints);

        txtfldPlaceToAddByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldPlaceToAddByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldPlaceToAddByCopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 193;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 68, 0, 0);
        panelCopRaiseOffence.add(txtfldPlaceToAddByCop, gridBagConstraints);

        comBoxOffenceIDToRaiseByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 104;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 70, 0, 0);
        panelCopRaiseOffence.add(comBoxOffenceIDToRaiseByCop, gridBagConstraints);

        comBoxPenaltyStatusToAddByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        comBoxPenaltyStatusToAddByCop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unpaid", "Paid" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(56, 70, 0, 0);
        panelCopRaiseOffence.add(comBoxPenaltyStatusToAddByCop, gridBagConstraints);

        btnProofToAddByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        btnProofToAddByCop.setText("Upload");
        btnProofToAddByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProofToAddByCopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = -7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 80, 0, 0);
        panelCopRaiseOffence.add(btnProofToAddByCop, gridBagConstraints);

        javax.swing.GroupLayout tabRaiseOffenceLayout = new javax.swing.GroupLayout(tabRaiseOffence);
        tabRaiseOffence.setLayout(tabRaiseOffenceLayout);
        tabRaiseOffenceLayout.setHorizontalGroup(
            tabRaiseOffenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCopRaiseOffence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tabRaiseOffenceLayout.setVerticalGroup(
            tabRaiseOffenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCopRaiseOffence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TCopOper.addTab("Raise offence", tabRaiseOffence);

        labelClearOffenceByCop.setFont(new java.awt.Font("Times New Roman", 3, 40)); // NOI18N
        labelClearOffenceByCop.setForeground(new java.awt.Color(204, 0, 51));
        labelClearOffenceByCop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClearOffenceByCop.setText("Clear Offence");

        txtfldSearchHistoryToClearByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldSearchHistoryToClearByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldSearchHistoryToClearByCopActionPerformed(evt);
            }
        });

        labelSearchHistoryToClearByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelSearchHistoryToClearByCop.setText("Registration Number");

        tableViewHistoryToClearByCaop.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tableViewHistoryToClearByCaop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Select", "Sl No.", "Offence Detail ID", "Offence Date and Time", "Place", "Proof", "Registration Number", "Offence ID", "Recorded By", "Penalty Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableViewHistoryToClearByCaop.setRowHeight(30);
        tableViewHistoryToClearByCaop.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tableViewHistoryToClearByCaop);

        btnClearOffence.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 20)); // NOI18N
        btnClearOffence.setText("Clear Offence");
        btnClearOffence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearOffenceActionPerformed(evt);
            }
        });

        btnSearchHistoryToClearByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        btnSearchHistoryToClearByCop.setText("View History");
        btnSearchHistoryToClearByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchHistoryToClearByCopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCopClearOffenceLayout = new javax.swing.GroupLayout(panelCopClearOffence);
        panelCopClearOffence.setLayout(panelCopClearOffenceLayout);
        panelCopClearOffenceLayout.setHorizontalGroup(
            panelCopClearOffenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCopClearOffenceLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(labelSearchHistoryToClearByCop, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfldSearchHistoryToClearByCop, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearchHistoryToClearByCop, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCopClearOffenceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClearOffence)
                .addGap(367, 367, 367))
            .addComponent(labelClearOffenceByCop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCopClearOffenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE))
        );
        panelCopClearOffenceLayout.setVerticalGroup(
            panelCopClearOffenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCopClearOffenceLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelClearOffenceByCop, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(panelCopClearOffenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchHistoryToClearByCop)
                    .addComponent(txtfldSearchHistoryToClearByCop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSearchHistoryToClearByCop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 531, Short.MAX_VALUE)
                .addComponent(btnClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(panelCopClearOffenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCopClearOffenceLayout.createSequentialGroup()
                    .addGap(287, 287, 287)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(294, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout tabClearOffenceLayout = new javax.swing.GroupLayout(tabClearOffence);
        tabClearOffence.setLayout(tabClearOffenceLayout);
        tabClearOffenceLayout.setHorizontalGroup(
            tabClearOffenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCopClearOffence, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tabClearOffenceLayout.setVerticalGroup(
            tabClearOffenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabClearOffenceLayout.createSequentialGroup()
                .addComponent(panelCopClearOffence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        TCopOper.addTab("Clear Offence", tabClearOffence);

        labelViewOffenceHistoryByCop.setFont(new java.awt.Font("Times New Roman", 3, 40)); // NOI18N
        labelViewOffenceHistoryByCop.setForeground(new java.awt.Color(204, 0, 51));
        labelViewOffenceHistoryByCop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelViewOffenceHistoryByCop.setText("View Offence History");

        labelSearchHistoryToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelSearchHistoryToViewByCop.setText("Registration Number");

        txtfldSearchHistoryToViewByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldSearchHistoryToViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldSearchHistoryToViewByCopActionPerformed(evt);
            }
        });

        togBtnViewHistoryToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 20)); // NOI18N
        togBtnViewHistoryToViewByCop.setText("View History");
        togBtnViewHistoryToViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togBtnViewHistoryToViewByCopActionPerformed(evt);
            }
        });

        tableViewHistoryToViewByCaop.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tableViewHistoryToViewByCaop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Sl No.", "Offence Detail ID", "Offence Date and Time", "Place", "Proof", "Registration Number", "Offence ID", "Recorded By", "Penalty Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableViewHistoryToViewByCaop.setRowHeight(30);
        tableViewHistoryToViewByCaop.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableViewHistoryToViewByCaop);

        javax.swing.GroupLayout panelViewHistoryByCopLayout = new javax.swing.GroupLayout(panelViewHistoryByCop);
        panelViewHistoryByCop.setLayout(panelViewHistoryByCopLayout);
        panelViewHistoryByCopLayout.setHorizontalGroup(
            panelViewHistoryByCopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewHistoryByCopLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labelViewOffenceHistoryByCop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
            .addGroup(panelViewHistoryByCopLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(labelSearchHistoryToViewByCop, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(txtfldSearchHistoryToViewByCop, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(togBtnViewHistoryToViewByCop, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addComponent(jScrollPane1)
        );
        panelViewHistoryByCopLayout.setVerticalGroup(
            panelViewHistoryByCopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewHistoryByCopLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelViewOffenceHistoryByCop, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelViewHistoryByCopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewHistoryByCopLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(panelViewHistoryByCopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSearchHistoryToViewByCop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfldSearchHistoryToViewByCop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewHistoryByCopLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(togBtnViewHistoryToViewByCop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addGap(164, 164, 164))
        );

        javax.swing.GroupLayout tabViewHistoryLayout = new javax.swing.GroupLayout(tabViewHistory);
        tabViewHistory.setLayout(tabViewHistoryLayout);
        tabViewHistoryLayout.setHorizontalGroup(
            tabViewHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelViewHistoryByCop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tabViewHistoryLayout.setVerticalGroup(
            tabViewHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelViewHistoryByCop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TCopOper.addTab("View offence history", tabViewHistory);

        scrollpaneViewDetails.setPreferredSize(tabAutoProfiles.getSize());

        panelDetails.setPreferredSize(tabAutoProfiles.getSize());
        panelDetails.setLayout(null);

        labelSearchDetailsToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelSearchDetailsToViewByCop.setText("Registration Number");
        panelDetails.add(labelSearchDetailsToViewByCop);
        labelSearchDetailsToViewByCop.setBounds(22, 76, 270, 35);

        labelAutoProfileByCop.setFont(new java.awt.Font("Times New Roman", 3, 40)); // NOI18N
        labelAutoProfileByCop.setForeground(new java.awt.Color(204, 0, 51));
        labelAutoProfileByCop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAutoProfileByCop.setText("View Details");
        panelDetails.add(labelAutoProfileByCop);
        labelAutoProfileByCop.setBounds(0, 11, 1463, 46);

        txtfldSearchDetailsToViewByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldSearchDetailsToViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldSearchDetailsToViewByCopActionPerformed(evt);
            }
        });
        panelDetails.add(txtfldSearchDetailsToViewByCop);
        txtfldSearchDetailsToViewByCop.setBounds(310, 70, 156, 41);

        checkVehicleDetailsByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        checkVehicleDetailsByCop.setText("Vehicle Details");
        panelDetails.add(checkVehicleDetailsByCop);
        checkVehicleDetailsByCop.setBounds(539, 78, 233, 30);

        checOwnerDetailsByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        checOwnerDetailsByCop.setText("Owner Details");
        panelDetails.add(checOwnerDetailsByCop);
        checOwnerDetailsByCop.setBounds(900, 80, 224, 30);
        panelDetails.add(jSeparator1);
        jSeparator1.setBounds(0, 128, 1890, 9);

        labelForViewOwnerDetails.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 3, 24)); // NOI18N
        labelForViewOwnerDetails.setText("Owner Details");
        panelDetails.add(labelForViewOwnerDetails);
        labelForViewOwnerDetails.setBounds(10, 150, 1890, 40);

        labelOwnerIDToviewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelOwnerIDToviewByCop.setText("Owner ID");
        panelDetails.add(labelOwnerIDToviewByCop);
        labelOwnerIDToviewByCop.setBounds(10, 209, 110, 30);

        labelIDTypeToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelIDTypeToViewByCop.setText("ID Type");
        panelDetails.add(labelIDTypeToViewByCop);
        labelIDTypeToViewByCop.setBounds(490, 210, 110, 30);

        labelDobToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelDobToViewByCop.setText("Date of Birth");
        panelDetails.add(labelDobToViewByCop);
        labelDobToViewByCop.setBounds(10, 280, 155, 30);

        labelFirstNameToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelFirstNameToViewByCop.setText("First Name");
        panelDetails.add(labelFirstNameToViewByCop);
        labelFirstNameToViewByCop.setBounds(880, 210, 160, 30);

        labelLastNameToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelLastNameToViewByCop.setText("Last Name");
        panelDetails.add(labelLastNameToViewByCop);
        labelLastNameToViewByCop.setBounds(1410, 210, 121, 30);

        labelGenderToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelGenderToViewByCop.setText("Gender");
        panelDetails.add(labelGenderToViewByCop);
        labelGenderToViewByCop.setBounds(490, 280, 110, 40);

        labelMobileNOToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelMobileNOToViewByCop.setText("Mobile Number");
        panelDetails.add(labelMobileNOToViewByCop);
        labelMobileNOToViewByCop.setBounds(880, 280, 200, 30);

        labelAddressToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelAddressToViewByCop.setText("Address");
        panelDetails.add(labelAddressToViewByCop);
        labelAddressToViewByCop.setBounds(10, 360, 110, 30);

        labelPincodeToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelPincodeToViewByCop.setText("Pincode");
        panelDetails.add(labelPincodeToViewByCop);
        labelPincodeToViewByCop.setBounds(490, 370, 110, 30);

        labelOccupationToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelOccupationToViewByCop.setText("Occupation");
        panelDetails.add(labelOccupationToViewByCop);
        labelOccupationToViewByCop.setBounds(1410, 280, 137, 30);

        txtfldPincodeToViewByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldPincodeToViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldPincodeToViewByCopActionPerformed(evt);
            }
        });
        panelDetails.add(txtfldPincodeToViewByCop);
        txtfldPincodeToViewByCop.setBounds(640, 370, 160, 30);

        txtfldMobileNoToViewByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldMobileNoToViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldMobileNoToViewByCopActionPerformed(evt);
            }
        });
        panelDetails.add(txtfldMobileNoToViewByCop);
        txtfldMobileNoToViewByCop.setBounds(1090, 280, 190, 30);

        txtfieldFirstNameToViewByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfieldFirstNameToViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldFirstNameToViewByCopActionPerformed(evt);
            }
        });
        panelDetails.add(txtfieldFirstNameToViewByCop);
        txtfieldFirstNameToViewByCop.setBounds(1090, 210, 190, 35);

        txtfldLastNameToViewByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldLastNameToViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldLastNameToViewByCopActionPerformed(evt);
            }
        });
        panelDetails.add(txtfldLastNameToViewByCop);
        txtfldLastNameToViewByCop.setBounds(1570, 210, 185, 36);

        txtfldOwnerIDToViewByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldOwnerIDToViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldOwnerIDToViewByCopActionPerformed(evt);
            }
        });
        panelDetails.add(txtfldOwnerIDToViewByCop);
        txtfldOwnerIDToViewByCop.setBounds(190, 210, 160, 30);

        txtfldOccupationToViewByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldOccupationToViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldOccupationToViewByCopActionPerformed(evt);
            }
        });
        panelDetails.add(txtfldOccupationToViewByCop);
        txtfldOccupationToViewByCop.setBounds(1570, 280, 190, 30);

        txtAreaAddressToViewByCop.setColumns(20);
        txtAreaAddressToViewByCop.setFont(new java.awt.Font("DejaVu Serif Condensed", 0, 20)); // NOI18N
        txtAreaAddressToViewByCop.setRows(50);
        jScrollPane2.setViewportView(txtAreaAddressToViewByCop);

        panelDetails.add(jScrollPane2);
        jScrollPane2.setBounds(190, 340, 190, 100);
        panelDetails.add(jSeparator2);
        jSeparator2.setBounds(0, 447, 1860, 20);

        labelForViewOwnerDetails4.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 3, 24)); // NOI18N
        labelForViewOwnerDetails4.setText("Vehicle Details");
        panelDetails.add(labelForViewOwnerDetails4);
        labelForViewOwnerDetails4.setBounds(0, 490, 520, 30);

        labelEngineNumberToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelEngineNumberToViewByCop.setText("Engine Number");
        panelDetails.add(labelEngineNumberToViewByCop);
        labelEngineNumberToViewByCop.setBounds(560, 580, 185, 30);

        labelTypeToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelTypeToViewByCop.setText("Vehicle Type");
        panelDetails.add(labelTypeToViewByCop);
        labelTypeToViewByCop.setBounds(10, 640, 180, 40);

        labelFuelUsedToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelFuelUsedToViewByCop.setText("Fuel Used");
        panelDetails.add(labelFuelUsedToViewByCop);
        labelFuelUsedToViewByCop.setBounds(1460, 580, 170, 30);

        labelChasisNoToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelChasisNoToViewByCop.setText("Chassis Number");
        panelDetails.add(labelChasisNoToViewByCop);
        labelChasisNoToViewByCop.setBounds(1050, 580, 190, 30);

        labelBrandToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelBrandToViewByCop.setText("Vehicle Brand");
        panelDetails.add(labelBrandToViewByCop);
        labelBrandToViewByCop.setBounds(560, 650, 200, 40);

        labelColorToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelColorToViewByCop.setText("Vehicle Color");
        panelDetails.add(labelColorToViewByCop);
        labelColorToViewByCop.setBounds(1050, 660, 160, 30);

        labelManuNameToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelManuNameToViewByCop.setText("Manufacturer Name");
        panelDetails.add(labelManuNameToViewByCop);
        labelManuNameToViewByCop.setBounds(10, 720, 236, 30);

        labelManuDateToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelManuDateToViewByCop.setText("Manufacture Date");
        panelDetails.add(labelManuDateToViewByCop);
        labelManuDateToViewByCop.setBounds(560, 720, 206, 40);

        labelModelNoToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelModelNoToViewByCop.setText("Model Number");
        panelDetails.add(labelModelNoToViewByCop);
        labelModelNoToViewByCop.setBounds(1460, 660, 170, 30);

        labelVehicleIDToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelVehicleIDToViewByCop.setText("Vehicle ID");
        panelDetails.add(labelVehicleIDToViewByCop);
        labelVehicleIDToViewByCop.setBounds(10, 570, 116, 30);

        txtfldEngineNumberToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        panelDetails.add(txtfldEngineNumberToViewByCop);
        txtfldEngineNumberToViewByCop.setBounds(810, 580, 162, 30);

        txtfldChasisNoToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        panelDetails.add(txtfldChasisNoToViewByCop);
        txtfldChasisNoToViewByCop.setBounds(1270, 580, 160, 30);

        txtfldFuelUsedToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        panelDetails.add(txtfldFuelUsedToViewByCop);
        txtfldFuelUsedToViewByCop.setBounds(1660, 580, 139, 30);

        txtfldBrandToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        txtfldBrandToViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldBrandToViewByCopActionPerformed(evt);
            }
        });
        panelDetails.add(txtfldBrandToViewByCop);
        txtfldBrandToViewByCop.setBounds(810, 660, 160, 30);

        txtfldColorToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        txtfldColorToViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldColorToViewByCopActionPerformed(evt);
            }
        });
        panelDetails.add(txtfldColorToViewByCop);
        txtfldColorToViewByCop.setBounds(1270, 660, 160, 30);

        txtfldManuNameToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        txtfldManuNameToViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldManuNameToViewByCopActionPerformed(evt);
            }
        });
        panelDetails.add(txtfldManuNameToViewByCop);
        txtfldManuNameToViewByCop.setBounds(280, 720, 200, 30);

        txtfldModelNoToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        txtfldModelNoToViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldModelNoToViewByCopActionPerformed(evt);
            }
        });
        panelDetails.add(txtfldModelNoToViewByCop);
        txtfldModelNoToViewByCop.setBounds(1660, 660, 150, 33);

        txtfldVehicleIDToViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        panelDetails.add(txtfldVehicleIDToViewByCop);
        txtfldVehicleIDToViewByCop.setBounds(280, 570, 190, 30);

        btnBackToHomeFromAutoProfilesByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        btnBackToHomeFromAutoProfilesByCop.setText("Back To Home");
        btnBackToHomeFromAutoProfilesByCop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBackToHomeFromAutoProfilesByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomeFromAutoProfilesByCopActionPerformed(evt);
            }
        });
        panelDetails.add(btnBackToHomeFromAutoProfilesByCop);
        btnBackToHomeFromAutoProfilesByCop.setBounds(810, 810, 210, 40);

        btnSearchDetailsoViewByCop.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 20)); // NOI18N
        btnSearchDetailsoViewByCop.setText("Search");
        btnSearchDetailsoViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDetailsoViewByCopActionPerformed(evt);
            }
        });
        panelDetails.add(btnSearchDetailsoViewByCop);
        btnSearchDetailsoViewByCop.setBounds(1380, 70, 124, 40);

        txtfldTypeToViewByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        panelDetails.add(txtfldTypeToViewByCop);
        txtfldTypeToViewByCop.setBounds(280, 650, 190, 30);

        txtfldenderToViewByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldenderToViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldenderToViewByCopActionPerformed(evt);
            }
        });
        panelDetails.add(txtfldenderToViewByCop);
        txtfldenderToViewByCop.setBounds(640, 280, 160, 33);

        txtfldDTypeToViewByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        panelDetails.add(txtfldDTypeToViewByCop);
        txtfldDTypeToViewByCop.setBounds(640, 210, 150, 33);

        txtfldDobToViewByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        panelDetails.add(txtfldDobToViewByCop);
        txtfldDobToViewByCop.setBounds(190, 280, 160, 35);

        txtfldManuDateToViewByCop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldManuDateToViewByCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldManuDateToViewByCopActionPerformed(evt);
            }
        });
        panelDetails.add(txtfldManuDateToViewByCop);
        txtfldManuDateToViewByCop.setBounds(810, 720, 166, 33);

        scrollpaneViewDetails.setViewportView(panelDetails);

        javax.swing.GroupLayout tabAutoProfilesLayout = new javax.swing.GroupLayout(tabAutoProfiles);
        tabAutoProfiles.setLayout(tabAutoProfilesLayout);
        tabAutoProfilesLayout.setHorizontalGroup(
            tabAutoProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollpaneViewDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 1886, Short.MAX_VALUE)
        );
        tabAutoProfilesLayout.setVerticalGroup(
            tabAutoProfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAutoProfilesLayout.createSequentialGroup()
                .addComponent(scrollpaneViewDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        TCopOper.addTab("Auto Profiles", tabAutoProfiles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TCopOper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TCopOper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void scaleImage() {
        ImageIcon icon = new ImageIcon("C:\\Users\\bhagya.shree\\OneDrive - iqgateway pvt ltd\\Training\\TMS\\Source Code\\TMS-source-code\\Presentation\\Presentation\\src\\tms\\presentation\\icons\\Cop.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(labelCopBgimg.getWidth(), labelCopBgimg.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        labelCopBgimg.setIcon(scaledIcon);
    }

    private void txtfldSearchHistoryToViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldSearchHistoryToViewByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldSearchHistoryToViewByCopActionPerformed

    private void togBtnViewHistoryToViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togBtnViewHistoryToViewByCopActionPerformed

            // TODO add your handling code here:
            String regNo = txtfldSearchHistoryToViewByCop.getText();
            if(!Validator.validateRegNo(regNo) || regNo.isEmpty())
                JOptionPane.showMessageDialog(this, "Invalid registration number", "Invalid input", JOptionPane.ERROR_MESSAGE);
            ArrayList<OffenceDetailEO> offDetails = null;
            try {
                offDetails = cop.fetchAllOffencesCommited(regNo);
            DefaultTableModel model = (DefaultTableModel) tableViewHistoryToViewByCaop.getModel();
            while (model.getRowCount() != 0) {
                model.removeRow(0);
            }
            int count = 1;
            for (OffenceDetailEO offenceDetailEO : offDetails) {
                model.addRow(new Object[]{
                    count,
                    offenceDetailEO.getOffenseDetailID(),
                    offenceDetailEO.getOffenseDateTime(),
                    offenceDetailEO.getPlace(),
                    offenceDetailEO.getImage(),
                    offenceDetailEO.getRegistration().getRegistrationID(),
                    offenceDetailEO.getOffense().getOffenseID(),
                    offenceDetailEO.getUser().getUserName(),
                    offenceDetailEO.getPenaltyStatus()
                });
                count++;
            }
        } catch (Exception ex) {
            Logger.getLogger(TrafficCopPage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "No Offences found..!", "Not found", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_togBtnViewHistoryToViewByCopActionPerformed

    private void txtfldSearchHistoryToClearByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldSearchHistoryToClearByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldSearchHistoryToClearByCopActionPerformed

    private void txtfldOccupationToViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldOccupationToViewByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldOccupationToViewByCopActionPerformed

    private void txtfldOwnerIDToViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldOwnerIDToViewByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldOwnerIDToViewByCopActionPerformed

    private void txtfldLastNameToViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldLastNameToViewByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldLastNameToViewByCopActionPerformed

    private void txtfieldFirstNameToViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldFirstNameToViewByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldFirstNameToViewByCopActionPerformed

    private void txtfldMobileNoToViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldMobileNoToViewByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldMobileNoToViewByCopActionPerformed

    private void txtfldPincodeToViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldPincodeToViewByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldPincodeToViewByCopActionPerformed

    private void txtfldSearchDetailsToViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldSearchDetailsToViewByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldSearchDetailsToViewByCopActionPerformed

    private void txtfldBrandToViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldBrandToViewByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldBrandToViewByCopActionPerformed

    private void btnBackToHomeFromAutoProfilesByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomeFromAutoProfilesByCopActionPerformed
        // TODO add your handling code here:
        TCopOper.setSelectedComponent(tabCopHome);
    }//GEN-LAST:event_btnBackToHomeFromAutoProfilesByCopActionPerformed

    private void txtfldPlaceToAddByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldPlaceToAddByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldPlaceToAddByCopActionPerformed

    private void txtfldVehicleNoToAddByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldVehicleNoToAddByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldVehicleNoToAddByCopActionPerformed

    private void txtfldRecordedByToAddByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldRecordedByToAddByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldRecordedByToAddByCopActionPerformed

    private void btnSearchHistoryToClearByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchHistoryToClearByCopActionPerformed

        // TODO add your handling code here:
        String regNo = txtfldSearchHistoryToClearByCop.getText();
        if (regNo.isEmpty() || !(Validator.validateRegNo(regNo))) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Registration number", "Ivalid Registration Number", JOptionPane.ERROR_MESSAGE);
            return;
        }
        clear(regNo);
    }//GEN-LAST:event_btnSearchHistoryToClearByCopActionPerformed

    private void btnClearOffenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearOffenceActionPerformed
        
            // TODO add your handling code here:
            String entRegNo = txtfldSearchHistoryToClearByCop.getText();
            if (entRegNo.isEmpty() || !(Validator.validateRegNo(entRegNo))) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Registration number", "Ivalid Registration Number", JOptionPane.ERROR_MESSAGE);
            return;
            }
            ArrayList<OffenceDetailEO> details;
        try {
            details = cop.fetchAllOffencesCommited(entRegNo);
        
            int count = 0;
            int row = 0;
            for (OffenceDetailEO detail : details) {
                if (detail.getPenaltyStatus().equalsIgnoreCase("Unpaid")) {
                    boolean isSelected = (boolean) tableViewHistoryToClearByCaop.getValueAt(row++, 0);
                    if (isSelected) {
                        detail.setPenaltyStatus("Paid");
                        cop.clearOffense(detail);
                        count++;
                    }
                }
            }
            if (count > 0) {
                System.out.println(count + " details updated..");
                JOptionPane.showMessageDialog(this, count + " details updated");
                clear(entRegNo);
            } else {
                System.out.println("No details found..!");
                JOptionPane.showMessageDialog(this, "No details found..!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(TrafficCopPage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Some error occurred while updating.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnClearOffenceActionPerformed
    private File uploadedFile = null;
    private void btnProofToAddByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProofToAddByCopActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Images", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filter);
        int returnValue = fileChooser.showOpenDialog(panelCopRaiseOffence);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            uploadedFile = fileChooser.getSelectedFile();
        } else {
            System.out.println("not opened");
            JOptionPane.showMessageDialog(this, "Some error occured", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProofToAddByCopActionPerformed

    private void btnRaiseOffenceByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseOffenceByCopActionPerformed
        // TODO add your handling code here:
            java.util.Date entOffDateNTime = (java.util.Date) spinOffenceDateTimeToAddByCop.getValue();
            Timestamp offDateTime = new Timestamp(entOffDateNTime.getTime());
            String place = txtfldPlaceToAddByCop.getText();

            byte[] proof = null;
            try (FileInputStream readFile = new FileInputStream(uploadedFile);) {
                int lines = readFile.available();
                proof = new byte[lines];
                readFile.read(proof);
            } catch (Exception ex) {
                 Logger.getLogger(ClerkPage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "File not found", "Some error occured", JOptionPane.ERROR_MESSAGE);
            return;
            }

            String registrationNo = txtfldVehicleNoToAddByCop.getText();
            RegistrationEO registration = null;
        try {
            registration = cop.fetchRegistrationDetails(registrationNo);
        } catch (Exception ex) {
            Logger.getLogger(ClerkPage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Some error occured", "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

            String offenceID = (String) comBoxOffenceIDToRaiseByCop.getSelectedItem();
            OffenceTypeEO offence = null;
        try {
            offence = cop.fetchOffenceByID(offenceID);
        } catch (Exception ex) {
            Logger.getLogger(ClerkPage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Some error occured", "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

            String recordedBy = txtfldRecordedByToAddByCop.getText();
            UserEO user = null;
        try {
            user = cop.fetchUserByID(recordedBy);
        } catch (Exception ex) {
            Logger.getLogger(ClerkPage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Some error occured", "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

            String status = (String) comBoxPenaltyStatusToAddByCop.getSelectedItem();
            
            if(place.isEmpty() || proof.length==0 || registrationNo.isEmpty() || offenceID.isEmpty() || recordedBy.isEmpty())
                JOptionPane.showMessageDialog(this, "Please fill all the details.", "Incomplete information", JOptionPane.ERROR_MESSAGE);
            
            OffenceDetailEO offenceDetail = new OffenceDetailEO("ABC", offDateTime, place, proof, registration, offence, user, status);
            int row = 0;
        try {
            row = cop.raiseOffence(offenceDetail);
        } catch (Exception ex) {
            Logger.getLogger(ClerkPage.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this,"Some error occured", "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
            if (row > 0) {
                System.out.println("Offence Raised...");
                JOptionPane.showMessageDialog(this, "Offence raised against " + registrationNo);
            } else {
                System.out.println("No offence raised...");
                JOptionPane.showMessageDialog(this, "Failed to raise an offence", "Some error occured", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnRaiseOffenceByCopActionPerformed

    private void btnSearchDetailsoViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDetailsoViewByCopActionPerformed
        // TODO add your handling code here:
        String entRegNo = txtfldSearchDetailsToViewByCop.getText();
        if (entRegNo.isEmpty() || !(Validator.validateRegNo(entRegNo))) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Registration number", "Ivalid Registration Number", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (checkVehicleDetailsByCop.isSelected()) {
            try {
                VehicleEO vehicle = cop.fetchVehicleDetails(entRegNo);
                txtfldVehicleIDToViewByCop.setText(Integer.toString(vehicle.getVehicleID()));
                txtfldEngineNumberToViewByCop.setText(vehicle.getEngineNumber());
                txtfldChasisNoToViewByCop.setText(vehicle.getChassisNumber());
                txtfldTypeToViewByCop.setText(vehicle.getVehicleType());
                txtfldBrandToViewByCop.setText(vehicle.getVehicleBrand());
                txtfldColorToViewByCop.setText(vehicle.getVehicleColor());
                txtfldFuelUsedToViewByCop.setText(vehicle.getFuelUsed());
                txtfldManuDateToViewByCop.setText(String.valueOf(vehicle.getManufacturDate()));
                txtfldManuNameToViewByCop.setText(vehicle.getManufacturerName());
                txtfldModelNoToViewByCop.setText(vehicle.getModelNo());
            } catch (Exception ex) {
                Logger.getLogger(TrafficCopPage.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Vehicle not found", "Invalid input", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            txtfldVehicleIDToViewByCop.setText("");
            txtfldEngineNumberToViewByCop.setText("");
            txtfldChasisNoToViewByCop.setText("");
            txtfldTypeToViewByCop.setText("");
            txtfldBrandToViewByCop.setText("");
            txtfldColorToViewByCop.setText("");
            txtfldFuelUsedToViewByCop.setText("");
            txtfldManuDateToViewByCop.setText("");
            txtfldManuNameToViewByCop.setText("");
            txtfldModelNoToViewByCop.setText("");
        }
        if (checOwnerDetailsByCop.isSelected()) {
            try {
                OwnerEO owner = cop.fetchOwnerDetails(entRegNo);
                txtfldOwnerIDToViewByCop.setText(owner.getOwnerID());
                txtfldDTypeToViewByCop.setText(owner.getIdType());
                txtfldDobToViewByCop.setText(String.valueOf(owner.getDob()));
                txtfieldFirstNameToViewByCop.setText(owner.getFName());
                txtfldLastNameToViewByCop.setText(owner.getLName());
                txtfldenderToViewByCop.setText(owner.getGender());
                txtfldMobileNoToViewByCop.setText(owner.getPhoneNumber());
                txtAreaAddressToViewByCop.setText(owner.getAddress());
                txtfldPincodeToViewByCop.setText(Integer.toString(owner.getPincode()));
                txtfldOccupationToViewByCop.setText(owner.getOccupation());
            } catch (Exception ex) {
                Logger.getLogger(TrafficCopPage.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Owner not found", "Invalid input", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            txtfldOwnerIDToViewByCop.setText("");
            txtfldDTypeToViewByCop.setText("");
            txtfldDobToViewByCop.setText("");
            txtfieldFirstNameToViewByCop.setText("");
            txtfldLastNameToViewByCop.setText("");
            txtfldenderToViewByCop.setText("");
            txtfldMobileNoToViewByCop.setText("");
            txtAreaAddressToViewByCop.setText("");
            txtfldPincodeToViewByCop.setText("");
            txtfldOccupationToViewByCop.setText("");
        }
    }//GEN-LAST:event_btnSearchDetailsoViewByCopActionPerformed

    private void txtfldenderToViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldenderToViewByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldenderToViewByCopActionPerformed

    private void txtfldModelNoToViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldModelNoToViewByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldModelNoToViewByCopActionPerformed

    private void txtfldManuDateToViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldManuDateToViewByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldManuDateToViewByCopActionPerformed

    private void txtfldManuNameToViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldManuNameToViewByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldManuNameToViewByCopActionPerformed

    private void txtfldColorToViewByCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldColorToViewByCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldColorToViewByCopActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginPage login = new LoginPage();
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrafficCopPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrafficCopPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrafficCopPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrafficCopPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrafficCopPage().setVisible(true);
            }
        });
    }

    private void addRoleList() {
        try {
            ArrayList<OffenceTypeEO> offType = cop.fetchAllOffenceTypes();
            for (OffenceTypeEO offenceTypeEO : offType) {
                comBoxOffenceIDToRaiseByCop.addItem(offenceTypeEO.getOffenseID());
            }
        } catch (Exception ex) {
            Logger.getLogger(TrafficCopPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private ArrayList<OffenceDetailEO> clear(String regNo) {

        ArrayList<OffenceDetailEO> details = new ArrayList<>();
        try {
            ArrayList<OffenceDetailEO> offDetails = cop.fetchAllOffencesCommited(regNo);
            DefaultTableModel model = (DefaultTableModel) tableViewHistoryToClearByCaop.getModel();
            while (model.getRowCount() != 0) {
                model.removeRow(0);
            }
            int count = 1;
            for (OffenceDetailEO offenceDetailEO : offDetails) {
                if (offenceDetailEO.getPenaltyStatus().equals("Unpaid")) {
                    model.addRow(new Object[]{
                        false,
                        count,
                        offenceDetailEO.getOffenseDetailID(),
                        offenceDetailEO.getOffenseDateTime(),
                        offenceDetailEO.getPlace(),
                        offenceDetailEO.getImage(),
                        offenceDetailEO.getRegistration().getRegistrationID(),
                        offenceDetailEO.getOffense().getOffenseID(),
                        offenceDetailEO.getUser().getUserName(),
                        offenceDetailEO.getPenaltyStatus()
                    });
                    details.add(offenceDetailEO);
                    count++;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ClerkPage.class.getName()).log(Level.SEVERE, null, ex);
        }

        return details;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TCopOper;
    private javax.swing.JButton btnBackToHomeFromAutoProfilesByCop;
    private javax.swing.JButton btnClearOffence;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProofToAddByCop;
    private javax.swing.JButton btnRaiseOffenceByCop;
    private javax.swing.JButton btnSearchDetailsoViewByCop;
    private javax.swing.JButton btnSearchHistoryToClearByCop;
    private javax.swing.JCheckBox checOwnerDetailsByCop;
    private javax.swing.JCheckBox checkVehicleDetailsByCop;
    private javax.swing.JComboBox<String> comBoxOffenceIDToRaiseByCop;
    private javax.swing.JComboBox<String> comBoxPenaltyStatusToAddByCop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelAddressToViewByCop;
    private javax.swing.JLabel labelAutoProfileByCop;
    private javax.swing.JLabel labelBrandToViewByCop;
    private javax.swing.JLabel labelChasisNoToViewByCop;
    private javax.swing.JLabel labelClearOffenceByCop;
    private javax.swing.JLabel labelColorToViewByCop;
    private javax.swing.JLabel labelCopBgimg;
    private javax.swing.JLabel labelDobToViewByCop;
    private javax.swing.JLabel labelEngineNumberToViewByCop;
    private javax.swing.JLabel labelFirstNameToViewByCop;
    private javax.swing.JLabel labelForViewOwnerDetails;
    private javax.swing.JLabel labelForViewOwnerDetails4;
    private javax.swing.JLabel labelFuelUsedToViewByCop;
    private javax.swing.JLabel labelGenderToViewByCop;
    private javax.swing.JLabel labelIDTypeToViewByCop;
    private javax.swing.JLabel labelLastNameToViewByCop;
    private javax.swing.JLabel labelManuDateToViewByCop;
    private javax.swing.JLabel labelManuNameToViewByCop;
    private javax.swing.JLabel labelMobileNOToViewByCop;
    private javax.swing.JLabel labelModelNoToViewByCop;
    private javax.swing.JLabel labelOccupationToViewByCop;
    private javax.swing.JLabel labelOffenceDateTimeToAddByCop;
    private javax.swing.JLabel labelOffenceIDToAddByCop;
    private javax.swing.JLabel labelOwnerIDToviewByCop;
    private javax.swing.JLabel labelPenaltyStatusToAddByCop;
    private javax.swing.JLabel labelPincodeToViewByCop;
    private javax.swing.JLabel labelPlaceToAddByCop;
    private javax.swing.JLabel labelProofToAddByCop;
    private javax.swing.JLabel labelRaiseOffenceByCopTitle;
    private javax.swing.JLabel labelRecordedByToAddByCop;
    private javax.swing.JLabel labelSearchDetailsToViewByCop;
    private javax.swing.JLabel labelSearchHistoryToClearByCop;
    private javax.swing.JLabel labelSearchHistoryToViewByCop;
    private javax.swing.JLabel labelTypeToViewByCop;
    private javax.swing.JLabel labelVehicleIDToViewByCop;
    private javax.swing.JLabel labelVehicleNoToAddByCop;
    private javax.swing.JLabel labelViewOffenceHistoryByCop;
    private javax.swing.JLabel labelWcCop;
    private javax.swing.JPanel panelCopClearOffence;
    private javax.swing.JPanel panelCopRaiseOffence;
    private javax.swing.JPanel panelDetails;
    private javax.swing.JPanel panelViewHistoryByCop;
    private javax.swing.JScrollPane scrollpaneViewDetails;
    private javax.swing.JSpinner spinOffenceDateTimeToAddByCop;
    private javax.swing.JPanel tabAutoProfiles;
    private javax.swing.JPanel tabClearOffence;
    private javax.swing.JPanel tabCopHome;
    private javax.swing.JPanel tabRaiseOffence;
    private javax.swing.JPanel tabViewHistory;
    private javax.swing.JTable tableViewHistoryToClearByCaop;
    private javax.swing.JTable tableViewHistoryToViewByCaop;
    private javax.swing.JToggleButton togBtnViewHistoryToViewByCop;
    private javax.swing.JTextArea txtAreaAddressToViewByCop;
    private javax.swing.JTextField txtfieldFirstNameToViewByCop;
    private javax.swing.JTextField txtfldBrandToViewByCop;
    private javax.swing.JTextField txtfldChasisNoToViewByCop;
    private javax.swing.JTextField txtfldColorToViewByCop;
    private javax.swing.JTextField txtfldDTypeToViewByCop;
    private javax.swing.JTextField txtfldDobToViewByCop;
    private javax.swing.JTextField txtfldEngineNumberToViewByCop;
    private javax.swing.JTextField txtfldFuelUsedToViewByCop;
    private javax.swing.JTextField txtfldLastNameToViewByCop;
    private javax.swing.JTextField txtfldManuDateToViewByCop;
    private javax.swing.JTextField txtfldManuNameToViewByCop;
    private javax.swing.JTextField txtfldMobileNoToViewByCop;
    private javax.swing.JTextField txtfldModelNoToViewByCop;
    private javax.swing.JTextField txtfldOccupationToViewByCop;
    private javax.swing.JTextField txtfldOwnerIDToViewByCop;
    private javax.swing.JTextField txtfldPincodeToViewByCop;
    private javax.swing.JTextField txtfldPlaceToAddByCop;
    private javax.swing.JTextField txtfldRecordedByToAddByCop;
    private javax.swing.JTextField txtfldSearchDetailsToViewByCop;
    private javax.swing.JTextField txtfldSearchHistoryToClearByCop;
    private javax.swing.JTextField txtfldSearchHistoryToViewByCop;
    private javax.swing.JTextField txtfldTypeToViewByCop;
    private javax.swing.JTextField txtfldVehicleIDToViewByCop;
    private javax.swing.JTextField txtfldVehicleNoToAddByCop;
    private javax.swing.JTextField txtfldenderToViewByCop;
    // End of variables declaration//GEN-END:variables

    private void viewHistory(String regNo) {
        try {
            ArrayList<OffenceDetailEO> offDetails = cop.fetchAllOffencesCommited(regNo);
            DefaultTableModel model = (DefaultTableModel) tableViewHistoryToClearByCaop.getModel();
            while (model.getRowCount() != 0) {
                model.removeRow(0);
            }
            int count = 1;
            for (OffenceDetailEO offenceDetailEO : offDetails) {
                model.addRow(new Object[]{
                    false,
                    count,
                    offenceDetailEO.getOffenseDetailID(),
                    offenceDetailEO.getOffenseDateTime(),
                    offenceDetailEO.getPlace(),
                    offenceDetailEO.getImage(),
                    offenceDetailEO.getRegistration().getRegistrationID(),
                    offenceDetailEO.getOffense().getOffenseID(),
                    offenceDetailEO.getUser().getUserName(),
                    offenceDetailEO.getPenaltyStatus()
                });
                count++;
            }
        } catch (Exception ex) {
            Logger.getLogger(TrafficCopPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
