/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms.presentation.Login;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tms.business.LoginOperation;
import tms.business.impl.LoginOperationsImpl;
import tms.persistence.entity.UserEO;

/**
 *
 * @author bhagya.shree
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        setVisible(Boolean.TRUE);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelResetPasswordtitle = new javax.swing.JLabel();
        labelPasswordToReset = new javax.swing.JLabel();
        labelUserNameToReset = new javax.swing.JLabel();
        txtfldUserNameToReset = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        comboxTypeToReset = new javax.swing.JComboBox<>();
        labelSelectTypeToReset = new javax.swing.JLabel();
        labelConfirmPassword = new javax.swing.JLabel();
        txtfldConfirmPassword = new javax.swing.JPasswordField();
        txtfldPasswordToReset = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelResetPasswordtitle.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        labelResetPasswordtitle.setForeground(new java.awt.Color(204, 0, 51));
        labelResetPasswordtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelResetPasswordtitle.setText("Reset Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 399;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(labelResetPasswordtitle, gridBagConstraints);

        labelPasswordToReset.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelPasswordToReset.setText("New Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 100, 0, 0);
        getContentPane().add(labelPasswordToReset, gridBagConstraints);

        labelUserNameToReset.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelUserNameToReset.setText("User Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 100, 0, 0);
        getContentPane().add(labelUserNameToReset, gridBagConstraints);

        txtfldUserNameToReset.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldUserNameToReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldUserNameToResetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 186;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 20, 0, 0);
        getContentPane().add(txtfldUserNameToReset, gridBagConstraints);

        btnReset.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 20)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 10, 0, 0);
        getContentPane().add(btnReset, gridBagConstraints);

        comboxTypeToReset.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        comboxTypeToReset.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User Name", "Email id", "Phone Number", " " }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(67, 22, 0, 0);
        getContentPane().add(comboxTypeToReset, gridBagConstraints);

        labelSelectTypeToReset.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelSelectTypeToReset.setText("Select type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(77, 100, 0, 0);
        getContentPane().add(labelSelectTypeToReset, gridBagConstraints);

        labelConfirmPassword.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelConfirmPassword.setText("Confirm Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 100, 0, 0);
        getContentPane().add(labelConfirmPassword, gridBagConstraints);

        txtfldConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldConfirmPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 186;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 20, 0, 0);
        getContentPane().add(txtfldConfirmPassword, gridBagConstraints);

        txtfldPasswordToReset.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 186;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 20, 0, 0);
        getContentPane().add(txtfldPasswordToReset, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        String chosenType = (String) comboxTypeToReset.getSelectedItem();
        String enteredUserName = txtfldUserNameToReset.getText();
        String newPassword = new String(txtfldPasswordToReset.getPassword());
        String confirmPasword = new String(txtfldConfirmPassword.getPassword());

        if (chosenType.isEmpty() || enteredUserName.isEmpty() || newPassword.isEmpty() || confirmPasword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields", "Incomplete Information", JOptionPane.ERROR_MESSAGE);
            return;
        }

        UserEO user = new UserEO();
        switch (chosenType) {
            case "Email id":
                user.setEmail(enteredUserName);
                break;
            case "Phone Number":
                user.setPhoneNumber(enteredUserName);
                break;
            case "User Name":
                user.setUserName(enteredUserName);
        }
        if (!newPassword.equals(confirmPasword))
            JOptionPane.showMessageDialog(this, "New password and Confirm password doesn't match", "Password missmatch", JOptionPane.ERROR_MESSAGE);
//            System.out.println("New Password and confirm password doesn't match");
        else {
            user.setPassword(newPassword);
            LoginOperation login = new LoginOperationsImpl();
            boolean isUpdated;
            try {
                isUpdated = login.resetPassword(user);

                if (isUpdated) {
                    System.out.println("Password updated");
                    JOptionPane.showMessageDialog(this, "Password updated.");
                } else {
                    System.out.println("Password not updated");
                    JOptionPane.showMessageDialog(this, "Some error occured", "IError", JOptionPane.ERROR_MESSAGE);
                }

                LoginPage loginPage = new LoginPage();
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtfldUserNameToResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldUserNameToResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldUserNameToResetActionPerformed

    private void txtfldConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldConfirmPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> comboxTypeToReset;
    private javax.swing.JLabel labelConfirmPassword;
    private javax.swing.JLabel labelPasswordToReset;
    private javax.swing.JLabel labelResetPasswordtitle;
    private javax.swing.JLabel labelSelectTypeToReset;
    private javax.swing.JLabel labelUserNameToReset;
    private javax.swing.JPasswordField txtfldConfirmPassword;
    private javax.swing.JPasswordField txtfldPasswordToReset;
    private javax.swing.JTextField txtfldUserNameToReset;
    // End of variables declaration//GEN-END:variables
}
