/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms.presentation.Login;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tms.business.AdminOperations;
import tms.business.LoginOperation;
import tms.business.impl.AdminOperationsImpl;
import tms.business.impl.LoginOperationsImpl;
import tms.persistence.entity.RoleEO;
import tms.persistence.entity.UserEO;
import tms.persistence.utility.Validator;
import tms.presentation.Admin.AdminFrame;
import tms.presentation.Clerk.ClerkPage;
import tms.presentation.RTO.RTOPage;
import tms.presentation.TrafficCop.TrafficCopPage;

/**
 *
 * @author bhagya.shree
 */
public class LoginPage extends javax.swing.JFrame {
    
    private final AdminOperations admin = new AdminOperationsImpl();
    
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        setVisible(Boolean.TRUE);
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
        addRoles();
        setResizable(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        labelUserName = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        labelRole = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtfldUser = new javax.swing.JTextField();
        txtfldPassword = new javax.swing.JPasswordField();
        comboRole = new javax.swing.JComboBox<>();
        labelTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 102, 255));
        setForeground(new java.awt.Color(102, 102, 255));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUserName.setBackground(new java.awt.Color(204, 204, 255));
        labelUserName.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelUserName.setForeground(new java.awt.Color(255, 255, 255));
        labelUserName.setText("User Name");
        jPanel1.add(labelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 160, 30));

        labelPassword.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelPassword.setText("Password");
        jPanel1.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 170, 30));

        labelRole.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelRole.setForeground(new java.awt.Color(255, 255, 255));
        labelRole.setText("Role");
        jPanel1.add(labelRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 130, 30));

        btnLogin.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 110, 40));

        txtfldUser.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        jPanel1.add(txtfldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 190, 30));

        txtfldPassword.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        txtfldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtfldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 180, 30));

        comboRole.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        jPanel1.add(comboRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 150, 30));

        labelTitle.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("Traffic Management System");
        jPanel1.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 810, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tms/presentation/icons/login.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 820, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String enteredUserName = txtfldUser.getText();
        String enteredPassword = new String(txtfldPassword.getPassword());
        String chosenRole = (String) comboRole.getSelectedItem();

        if (chosenRole == null || enteredUserName.isEmpty() || enteredPassword.length() == 0) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields", "Incomplete Information", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!Validator.validatePassword(enteredPassword)) {
            JOptionPane.showMessageDialog(this, enteredPassword + " is not a valid password.\nPassword must be strong with alphabets, caps, special symbols, numbers, and minimum 8 characters and less than 16 characters.", "Invalid password", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        System.out.println(enteredUserName + "\t" + enteredPassword + "\t" + chosenRole);

        UserEO user = new UserEO();
        user.setUserName(enteredUserName);
        user.setPassword(enteredPassword);
        RoleEO role = new RoleEO();
        role.setRoleName(chosenRole);
        user.setRole(role);

        LoginOperation login = new LoginOperationsImpl();
        try {
            boolean isValidUser = login.loginUser(user);

            if (isValidUser) {
                System.out.println("Valid user");
                switch (chosenRole) {
                    case "Admin":
                        AdminFrame admin = new AdminFrame();
                        break;
                    case "Traffic Cop":
                        TrafficCopPage cop = new TrafficCopPage();
                        break;
                    case "RTO Officer":
                        RTOPage rto = new RTOPage();
                        break;
                    case "Clerk":
                        ClerkPage clerk = new ClerkPage();
                        break;
                }
//            JOptionPane.showMessageDialog(this, "Login Successfull..!");
                this.dispose();
            } else {
                System.out.println("Not a valid user");
                JOptionPane.showMessageDialog(this, "Invalid username or password or role", "Invalid credentials", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An error occurred while logging in", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Print the stack trace for debugging
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtfldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JPasswordField txtfldPassword;
    private javax.swing.JTextField txtfldUser;
    // End of variables declaration//GEN-END:variables

    private void addRoles() {
        try {
            ArrayList<RoleEO> roles = admin.findAllRoles();
            for (RoleEO role : roles) {
                comboRole.addItem(role.getRoleName());
            }
        } catch (Exception ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}
