/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms.presentation.RTO;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tms.business.RTOOperations;
import tms.business.impl.RTOOperationsImpl;
import tms.persistence.entity.OwnerEO;

/**
 *
 * @author bhagya.shree
 */
public class Owner extends javax.swing.JFrame {
    
    private final RTOOperations rto = new RTOOperationsImpl();

    /**
     * Creates new form Owner
     */
    public Owner() {
        initComponents();
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(Boolean.TRUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelAddNewOwner = new javax.swing.JPanel();
        labelAddOwnerTitle = new javax.swing.JLabel();
        labelOwnerIDToAddByRTO = new javax.swing.JLabel();
        labelIDTypeToAddByRTO = new javax.swing.JLabel();
        labelDobToAddByRTO = new javax.swing.JLabel();
        labelFirstNameToAddByRTO = new javax.swing.JLabel();
        labelLastNameToAddByRTO = new javax.swing.JLabel();
        labelGenderToAddByRTO = new javax.swing.JLabel();
        labelMobileNOToAddByRTO = new javax.swing.JLabel();
        labelAddressToAddByRTO = new javax.swing.JLabel();
        labelPincodeToAddByRTO = new javax.swing.JLabel();
        labelOccupationToAddByRTO = new javax.swing.JLabel();
        txtfldPincodeToAddByRTO = new javax.swing.JTextField();
        comBoxGenderToAddByRTO = new javax.swing.JComboBox<>();
        txtfldMobileNoToAddByRTO = new javax.swing.JTextField();
        txtfieldFirstNameToAddByRTO = new javax.swing.JTextField();
        txtfldLastNameToAddByRTO = new javax.swing.JTextField();
        txtfldOwnerIDToAddByRTO = new javax.swing.JTextField();
        txtfldOccupationToAddByRTO = new javax.swing.JTextField();
        comboxIDTypeToAddByRTO = new javax.swing.JComboBox<>();
        btnAddOwnerToAddByRTO = new javax.swing.JButton();
        jDateChooserOwnerDob = new com.toedter.calendar.JDateChooser();
        txtareaAddressToAddByRTO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAddNewOwner.setLayout(new java.awt.GridBagLayout());

        labelAddOwnerTitle.setFont(new java.awt.Font("Times New Roman", 3, 40)); // NOI18N
        labelAddOwnerTitle.setForeground(new java.awt.Color(204, 0, 51));
        labelAddOwnerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAddOwnerTitle.setText("Add New Owner");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.ipadx = 819;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 0, 0, 2);
        panelAddNewOwner.add(labelAddOwnerTitle, gridBagConstraints);

        labelOwnerIDToAddByRTO.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelOwnerIDToAddByRTO.setText("Owner ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(137, 10, 0, 0);
        panelAddNewOwner.add(labelOwnerIDToAddByRTO, gridBagConstraints);

        labelIDTypeToAddByRTO.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelIDTypeToAddByRTO.setText("ID Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(137, 60, 0, 0);
        panelAddNewOwner.add(labelIDTypeToAddByRTO, gridBagConstraints);

        labelDobToAddByRTO.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelDobToAddByRTO.setText("Date of Birth");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 0, 0);
        panelAddNewOwner.add(labelDobToAddByRTO, gridBagConstraints);

        labelFirstNameToAddByRTO.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelFirstNameToAddByRTO.setText("First Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 0, 0);
        panelAddNewOwner.add(labelFirstNameToAddByRTO, gridBagConstraints);

        labelLastNameToAddByRTO.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelLastNameToAddByRTO.setText("Last Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 60, 0, 0);
        panelAddNewOwner.add(labelLastNameToAddByRTO, gridBagConstraints);

        labelGenderToAddByRTO.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelGenderToAddByRTO.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 60, 0, 0);
        panelAddNewOwner.add(labelGenderToAddByRTO, gridBagConstraints);

        labelMobileNOToAddByRTO.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelMobileNOToAddByRTO.setText("Mobile Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 0, 0);
        panelAddNewOwner.add(labelMobileNOToAddByRTO, gridBagConstraints);

        labelAddressToAddByRTO.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelAddressToAddByRTO.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 20, 0, 0);
        panelAddNewOwner.add(labelAddressToAddByRTO, gridBagConstraints);

        labelPincodeToAddByRTO.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelPincodeToAddByRTO.setText("Pincode");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 60, 0, 0);
        panelAddNewOwner.add(labelPincodeToAddByRTO, gridBagConstraints);

        labelOccupationToAddByRTO.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 22)); // NOI18N
        labelOccupationToAddByRTO.setText("Occupation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 60, 0, 0);
        panelAddNewOwner.add(labelOccupationToAddByRTO, gridBagConstraints);

        txtfldPincodeToAddByRTO.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldPincodeToAddByRTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldPincodeToAddByRTOActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 30, 0, 0);
        panelAddNewOwner.add(txtfldPincodeToAddByRTO, gridBagConstraints);

        comBoxGenderToAddByRTO.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 18)); // NOI18N
        comBoxGenderToAddByRTO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        comBoxGenderToAddByRTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxGenderToAddByRTOActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 30, 0, 0);
        panelAddNewOwner.add(comBoxGenderToAddByRTO, gridBagConstraints);

        txtfldMobileNoToAddByRTO.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldMobileNoToAddByRTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldMobileNoToAddByRTOActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 0, 0);
        panelAddNewOwner.add(txtfldMobileNoToAddByRTO, gridBagConstraints);

        txtfieldFirstNameToAddByRTO.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfieldFirstNameToAddByRTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldFirstNameToAddByRTOActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 0, 0);
        panelAddNewOwner.add(txtfieldFirstNameToAddByRTO, gridBagConstraints);

        txtfldLastNameToAddByRTO.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldLastNameToAddByRTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldLastNameToAddByRTOActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 30, 0, 0);
        panelAddNewOwner.add(txtfldLastNameToAddByRTO, gridBagConstraints);

        txtfldOwnerIDToAddByRTO.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldOwnerIDToAddByRTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldOwnerIDToAddByRTOActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(137, 10, 0, 0);
        panelAddNewOwner.add(txtfldOwnerIDToAddByRTO, gridBagConstraints);

        txtfldOccupationToAddByRTO.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldOccupationToAddByRTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldOccupationToAddByRTOActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 153;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 30, 0, 0);
        panelAddNewOwner.add(txtfldOccupationToAddByRTO, gridBagConstraints);

        comboxIDTypeToAddByRTO.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 18)); // NOI18N
        comboxIDTypeToAddByRTO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AAdhar Card", "PanCard" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = -34;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(137, 30, 0, 0);
        panelAddNewOwner.add(comboxIDTypeToAddByRTO, gridBagConstraints);

        btnAddOwnerToAddByRTO.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 20)); // NOI18N
        btnAddOwnerToAddByRTO.setText("Add Owner");
        btnAddOwnerToAddByRTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOwnerToAddByRTOActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(150, 0, 384, 0);
        panelAddNewOwner.add(btnAddOwnerToAddByRTO, gridBagConstraints);

        jDateChooserOwnerDob.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 20, 0, 0);
        panelAddNewOwner.add(jDateChooserOwnerDob, gridBagConstraints);

        txtareaAddressToAddByRTO.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 10, 0, 0);
        panelAddNewOwner.add(txtareaAddressToAddByRTO, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1186, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAddNewOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 1186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1192, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAddNewOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 1192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfldPincodeToAddByRTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldPincodeToAddByRTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldPincodeToAddByRTOActionPerformed

    private void comBoxGenderToAddByRTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxGenderToAddByRTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxGenderToAddByRTOActionPerformed

    private void txtfldMobileNoToAddByRTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldMobileNoToAddByRTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldMobileNoToAddByRTOActionPerformed

    private void txtfieldFirstNameToAddByRTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldFirstNameToAddByRTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldFirstNameToAddByRTOActionPerformed

    private void txtfldLastNameToAddByRTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldLastNameToAddByRTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldLastNameToAddByRTOActionPerformed

    private void txtfldOwnerIDToAddByRTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldOwnerIDToAddByRTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldOwnerIDToAddByRTOActionPerformed

    private void txtfldOccupationToAddByRTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldOccupationToAddByRTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldOccupationToAddByRTOActionPerformed

    private void btnAddOwnerToAddByRTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOwnerToAddByRTOActionPerformed
        try {
            // TODO add your handling code here:
            OwnerEO owner = new OwnerEO();
            owner.setOwnerID(txtfldOwnerIDToAddByRTO.getText());
            owner.setIdType((String) comboxIDTypeToAddByRTO.getSelectedItem());
            owner.setFName(txtfieldFirstNameToAddByRTO.getText());
            owner.setLName(txtfldLastNameToAddByRTO.getText());

            java.util.Date entDate = jDateChooserOwnerDob.getDate();
            java.sql.Date dob = new java.sql.Date(entDate.getTime());
            owner.setDob(dob);

            owner.setGender((String) comBoxGenderToAddByRTO.getSelectedItem());
            owner.setPhoneNumber(txtfldMobileNoToAddByRTO.getText());
            owner.setOccupation(txtfldOccupationToAddByRTO.getText());
            owner.setAddress(txtareaAddressToAddByRTO.getText());
            owner.setPincode(Integer.parseInt(txtfldPincodeToAddByRTO.getText()));

            int rows = rto.addNewOwner(owner);
            if (rows > 0) {
                System.out.println("New Owner added..");
                JOptionPane.showMessageDialog(this, "New Owner added.");
                this.dispose();
            }
            else {
                System.out.println("Owner not added..");
                JOptionPane.showMessageDialog(this, "Owner details not added..", "Some error occured", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(RTOPage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Please fill all the details", "Invalid input", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btnAddOwnerToAddByRTOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Owner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOwnerToAddByRTO;
    private javax.swing.JComboBox<String> comBoxGenderToAddByRTO;
    private javax.swing.JComboBox<String> comboxIDTypeToAddByRTO;
    private com.toedter.calendar.JDateChooser jDateChooserOwnerDob;
    private javax.swing.JLabel labelAddOwnerTitle;
    private javax.swing.JLabel labelAddressToAddByRTO;
    private javax.swing.JLabel labelDobToAddByRTO;
    private javax.swing.JLabel labelFirstNameToAddByRTO;
    private javax.swing.JLabel labelGenderToAddByRTO;
    private javax.swing.JLabel labelIDTypeToAddByRTO;
    private javax.swing.JLabel labelLastNameToAddByRTO;
    private javax.swing.JLabel labelMobileNOToAddByRTO;
    private javax.swing.JLabel labelOccupationToAddByRTO;
    private javax.swing.JLabel labelOwnerIDToAddByRTO;
    private javax.swing.JLabel labelPincodeToAddByRTO;
    private javax.swing.JPanel panelAddNewOwner;
    private javax.swing.JTextField txtareaAddressToAddByRTO;
    private javax.swing.JTextField txtfieldFirstNameToAddByRTO;
    private javax.swing.JTextField txtfldLastNameToAddByRTO;
    private javax.swing.JTextField txtfldMobileNoToAddByRTO;
    private javax.swing.JTextField txtfldOccupationToAddByRTO;
    private javax.swing.JTextField txtfldOwnerIDToAddByRTO;
    private javax.swing.JTextField txtfldPincodeToAddByRTO;
    // End of variables declaration//GEN-END:variables
}
