/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms.presentation.RTO;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tms.business.RTOOperations;
import tms.business.impl.RTOOperationsImpl;
import tms.persistence.entity.VehicleEO;

/**
 *
 * @author bhagya.shree
 */
public class Vehicle extends javax.swing.JFrame {

    private final RTOOperations rto = new RTOOperationsImpl();

    /**
     * Creates new form Vehicle
     */
    public Vehicle() {
        initComponents();
        setVisible(Boolean.TRUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelNewVehicle = new javax.swing.JPanel();
        labelAddNewVehicleTitle = new javax.swing.JLabel();
        labelVehicleTypeToAdd = new javax.swing.JLabel();
        labelVehicleColorToAdd = new javax.swing.JLabel();
        labelManuDateToAdd = new javax.swing.JLabel();
        labelModelNoToAdd = new javax.swing.JLabel();
        labelChassisNumberToAdd = new javax.swing.JLabel();
        labelVehicleBrandToAdd = new javax.swing.JLabel();
        labelFuelUsedToAdd = new javax.swing.JLabel();
        labelManuNameToAdd = new javax.swing.JLabel();
        labelEngineNoToAdd = new javax.swing.JLabel();
        btnAddNewVehicle = new javax.swing.JButton();
        txtfldChassisNoToAdd = new javax.swing.JTextField();
        txtfldVehicleBrandToAdd = new javax.swing.JTextField();
        txtfldFuelUsedToAdd = new javax.swing.JTextField();
        txtfldManuNameToAdd = new javax.swing.JTextField();
        txtfldModelNoToAdd = new javax.swing.JTextField();
        txtfldVehicleTypeToAdd = new javax.swing.JTextField();
        txtfldVehicleColorToAdd = new javax.swing.JTextField();
        txtfldEngineNoToAdd = new javax.swing.JTextField();
        jDateChManuDateToAdd = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelNewVehicle.setLayout(new java.awt.GridBagLayout());

        labelAddNewVehicleTitle.setFont(new java.awt.Font("Times New Roman", 3, 40)); // NOI18N
        labelAddNewVehicleTitle.setForeground(new java.awt.Color(204, 0, 51));
        labelAddNewVehicleTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAddNewVehicleTitle.setText("Add New Vehicle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 795;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        panelNewVehicle.add(labelAddNewVehicleTitle, gridBagConstraints);

        labelVehicleTypeToAdd.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelVehicleTypeToAdd.setText("Vehicle Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 30, 0, 0);
        panelNewVehicle.add(labelVehicleTypeToAdd, gridBagConstraints);

        labelVehicleColorToAdd.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelVehicleColorToAdd.setText("Vehicle Color");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 30, 0, 0);
        panelNewVehicle.add(labelVehicleColorToAdd, gridBagConstraints);

        labelManuDateToAdd.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelManuDateToAdd.setText("Manufacture Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 20, 0, 0);
        panelNewVehicle.add(labelManuDateToAdd, gridBagConstraints);

        labelModelNoToAdd.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelModelNoToAdd.setText("Model Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 20, 0, 0);
        panelNewVehicle.add(labelModelNoToAdd, gridBagConstraints);

        labelChassisNumberToAdd.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelChassisNumberToAdd.setText("Chassis Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(100, 60, 0, 0);
        panelNewVehicle.add(labelChassisNumberToAdd, gridBagConstraints);

        labelVehicleBrandToAdd.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelVehicleBrandToAdd.setText("Vehicle Brand");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 60, 0, 0);
        panelNewVehicle.add(labelVehicleBrandToAdd, gridBagConstraints);

        labelFuelUsedToAdd.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelFuelUsedToAdd.setText("Fuel Used");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 60, 0, 0);
        panelNewVehicle.add(labelFuelUsedToAdd, gridBagConstraints);

        labelManuNameToAdd.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelManuNameToAdd.setText("Manufacturer Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 50, 0, 0);
        panelNewVehicle.add(labelManuNameToAdd, gridBagConstraints);

        labelEngineNoToAdd.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 22)); // NOI18N
        labelEngineNoToAdd.setText("Engine Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 30, 0, 0);
        panelNewVehicle.add(labelEngineNoToAdd, gridBagConstraints);

        btnAddNewVehicle.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 20)); // NOI18N
        btnAddNewVehicle.setText("Add ");
        btnAddNewVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewVehicleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 57;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(110, 10, 481, 0);
        panelNewVehicle.add(btnAddNewVehicle, gridBagConstraints);

        txtfldChassisNoToAdd.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(90, 20, 0, 0);
        panelNewVehicle.add(txtfldChassisNoToAdd, gridBagConstraints);

        txtfldVehicleBrandToAdd.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 20, 0, 0);
        panelNewVehicle.add(txtfldVehicleBrandToAdd, gridBagConstraints);

        txtfldFuelUsedToAdd.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 20, 0, 0);
        panelNewVehicle.add(txtfldFuelUsedToAdd, gridBagConstraints);

        txtfldManuNameToAdd.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 20, 0, 0);
        panelNewVehicle.add(txtfldManuNameToAdd, gridBagConstraints);

        txtfldModelNoToAdd.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtfldModelNoToAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldModelNoToAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 0, 0);
        panelNewVehicle.add(txtfldModelNoToAdd, gridBagConstraints);

        txtfldVehicleTypeToAdd.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 0, 0);
        panelNewVehicle.add(txtfldVehicleTypeToAdd, gridBagConstraints);

        txtfldVehicleColorToAdd.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 0, 0);
        panelNewVehicle.add(txtfldVehicleColorToAdd, gridBagConstraints);

        txtfldEngineNoToAdd.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(90, 20, 0, 0);
        panelNewVehicle.add(txtfldEngineNoToAdd, gridBagConstraints);

        jDateChManuDateToAdd.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 0, 0);
        panelNewVehicle.add(jDateChManuDateToAdd, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1297, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelNewVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 1297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1554, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelNewVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 1554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewVehicleActionPerformed
        try {
            // TODO add your handling code here:
            String entEngNo = txtfldEngineNoToAdd.getText();
            String entChaNo = txtfldChassisNoToAdd.getText();
            String type = txtfldVehicleTypeToAdd.getText();
            String brand = txtfldVehicleBrandToAdd.getText();
            String color = txtfldVehicleColorToAdd.getText();
            String fuel = txtfldFuelUsedToAdd.getText();

            java.util.Date entDate = jDateChManuDateToAdd.getDate();
            java.sql.Date manuDate = new java.sql.Date(entDate.getTime());

            String manuName = txtfldManuNameToAdd.getText();
            String modelNo = txtfldModelNoToAdd.getText();

            VehicleEO vehicle = new VehicleEO(123, entEngNo, entChaNo, type, brand, color, fuel, manuDate, manuName, modelNo);
            int row = rto.addNewVehicle(vehicle);
            if (row > 0) {
                System.out.println("Vehicle is added..");
                JOptionPane.showMessageDialog(this, "Vehicle details added..");
                this.dispose();
            }
            else {
                System.out.println("Vehicle is not added.");
                JOptionPane.showMessageDialog(this, "Vehicle details not added..", "Some error occured", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(RTOPage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Some error occurred", "Invalid input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddNewVehicleActionPerformed

    private void txtfldModelNoToAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldModelNoToAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldModelNoToAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewVehicle;
    private com.toedter.calendar.JDateChooser jDateChManuDateToAdd;
    private javax.swing.JLabel labelAddNewVehicleTitle;
    private javax.swing.JLabel labelChassisNumberToAdd;
    private javax.swing.JLabel labelEngineNoToAdd;
    private javax.swing.JLabel labelFuelUsedToAdd;
    private javax.swing.JLabel labelManuDateToAdd;
    private javax.swing.JLabel labelManuNameToAdd;
    private javax.swing.JLabel labelModelNoToAdd;
    private javax.swing.JLabel labelVehicleBrandToAdd;
    private javax.swing.JLabel labelVehicleColorToAdd;
    private javax.swing.JLabel labelVehicleTypeToAdd;
    private javax.swing.JPanel panelNewVehicle;
    private javax.swing.JTextField txtfldChassisNoToAdd;
    private javax.swing.JTextField txtfldEngineNoToAdd;
    private javax.swing.JTextField txtfldFuelUsedToAdd;
    private javax.swing.JTextField txtfldManuNameToAdd;
    private javax.swing.JTextField txtfldModelNoToAdd;
    private javax.swing.JTextField txtfldVehicleBrandToAdd;
    private javax.swing.JTextField txtfldVehicleColorToAdd;
    private javax.swing.JTextField txtfldVehicleTypeToAdd;
    // End of variables declaration//GEN-END:variables
}
